# Generated by Django 6.0.5 on 2026-06-03 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_pruduct_size_alter_order_date_alter_pruduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruduct',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 6, 3, 13, 47, 55, 410698)),
        ),
    ]
